/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as AlertsIdRouteImport } from './routes/alerts.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/documentation': typeof DocumentationRoute
  '/logs': typeof LogsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/logs': typeof LogsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/documentation': typeof DocumentationRoute
  '/logs': typeof LogsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/customers'
    | '/documentation'
    | '/logs'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/alerts/$id'
    | '/customers/$id'
    | '/alerts/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/logs'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/alerts/$id'
    | '/customers/$id'
    | '/alerts'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/customers'
    | '/documentation'
    | '/logs'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/alerts/$id'
    | '/customers/$id'
    | '/alerts/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DocumentationRoute: typeof DocumentationRoute
  LogsRoute: typeof LogsRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof AlertsRoute
    }
  }
}

interface AlertsRouteChildren {
  AlertsIdRoute: typeof AlertsIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsIdRoute: AlertsIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DocumentationRoute: DocumentationRoute,
  LogsRoute: LogsRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
