import type {
  Alert,
  Customer,
  GraphEdge,
  GraphNode,
  KYCDriftRecord,
  AIReasoningTrace,
  GovernanceRecord,
} from "./types";

export const customers: Customer[] = [
  {
    id: "spacex",
    companyName: "SpaceX",
    legalName: "Space Exploration Technologies Corp.",
    responsiblePerson: "Elon Musk",
    responsiblePersonRole: "CEO / Authorized Representative",
    industry: "Aerospace",
    country: "United States",
    onboardedDate: "Aug 12, 2023",
    kycStatus: "Verified",
    riskStatus: "elevated",
    riskScore: 81,
    driftPercent: 69,
    driftSeverity: "high",
    lastUpdated: "2 min ago",
    transactionVolume: "$245M",
    companyType: "Corporate",
    isNewlyOnboarded: true,
    profileBuildingStatus: "Profile building active",
    trend: "up",
  },
  {
    id: "amazon",
    companyName: "Amazon",
    legalName: "Amazon.com, Inc.",
    responsiblePerson: "Jeff Bezos",
    responsiblePersonRole: "Founder / Authorized Rep.",
    industry: "E-commerce",
    country: "United States",
    onboardedDate: "Jan 04, 2024",
    kycStatus: "Verified",
    riskStatus: "low",
    riskScore: 18,
    driftPercent: 12,
    driftSeverity: "low",
    lastUpdated: "18 min ago",
    transactionVolume: "$1.2B",
    companyType: "Corporate",
    isNewlyOnboarded: true,
    profileBuildingStatus: "Profile building active",
    trend: "flat",
  },
  {
    id: "nvidia",
    companyName: "NVIDIA",
    legalName: "NVIDIA Corporation",
    responsiblePerson: "Jensen Huang",
    responsiblePersonRole: "CEO",
    industry: "Semiconductors",
    country: "United States",
    onboardedDate: "Mar 21, 2024",
    kycStatus: "Verified",
    riskStatus: "medium",
    riskScore: 47,
    driftPercent: 31,
    driftSeverity: "medium",
    lastUpdated: "11 min ago",
    transactionVolume: "$612M",
    companyType: "Corporate",
    isNewlyOnboarded: true,
    profileBuildingStatus: "Profile building active",
    trend: "up",
  },
  {
    id: "binance",
    companyName: "Binance Holdings",
    legalName: "Binance Holdings Ltd.",
    responsiblePerson: "Richard Teng",
    responsiblePersonRole: "CEO / Authorized Representative",
    industry: "Crypto Exchange",
    country: "Cayman Islands",
    onboardedDate: "Oct 02, 2024",
    kycStatus: "Pending",
    riskStatus: "high",
    riskScore: 92,
    driftPercent: 84,
    driftSeverity: "critical",
    lastUpdated: "4 min ago",
    transactionVolume: "$3.1B",
    companyType: "Corporate",
    isNewlyOnboarded: true,
    profileBuildingStatus: "Profile building active",
    trend: "up",
  },
  {
    id: "tesla",
    companyName: "Tesla",
    legalName: "Tesla, Inc.",
    responsiblePerson: "Elon Musk",
    responsiblePersonRole: "CEO",
    industry: "Automotive",
    country: "United States",
    onboardedDate: "Jul 14, 2020",
    kycStatus: "Verified",
    riskStatus: "medium",
    riskScore: 52,
    driftPercent: 42,
    driftSeverity: "medium",
    lastUpdated: "9 min ago",
    transactionVolume: "$880M",
    companyType: "Corporate",
    trend: "up",
  },
  {
    id: "openai",
    companyName: "OpenAI",
    legalName: "OpenAI, L.L.C.",
    responsiblePerson: "Sam Altman",
    responsiblePersonRole: "CEO / Authorized Representative",
    industry: "Artificial Intelligence",
    country: "United States",
    onboardedDate: "May 04, 2023",
    kycStatus: "Verified",
    riskStatus: "elevated",
    riskScore: 73,
    driftPercent: 57,
    driftSeverity: "high",
    lastUpdated: "6 min ago",
    transactionVolume: "$310M",
    companyType: "Corporate",
    trend: "up",
  },
  {
    id: "apple",
    companyName: "Apple",
    legalName: "Apple Inc.",
    responsiblePerson: "Tim Cook",
    responsiblePersonRole: "CEO",
    industry: "Consumer Electronics",
    country: "United States",
    onboardedDate: "Feb 11, 2019",
    kycStatus: "Verified",
    riskStatus: "low",
    riskScore: 14,
    driftPercent: 9,
    driftSeverity: "low",
    lastUpdated: "22 min ago",
    transactionVolume: "$2.4B",
    companyType: "Corporate",
    trend: "flat",
  },
  {
    id: "meta",
    companyName: "Meta",
    legalName: "Meta Platforms, Inc.",
    responsiblePerson: "Mark Zuckerberg",
    responsiblePersonRole: "CEO / Authorized Representative",
    industry: "Social Media",
    country: "United States",
    onboardedDate: "Aug 22, 2021",
    kycStatus: "Verified",
    riskStatus: "medium",
    riskScore: 49,
    driftPercent: 36,
    driftSeverity: "medium",
    lastUpdated: "14 min ago",
    transactionVolume: "$1.05B",
    companyType: "Corporate",
    trend: "down",
  },
];

export const alerts: Alert[] = [
  {
    id: "alert_001",
    customerId: "spacex",
    customerName: "SpaceX",
    title: "New beneficial owner identified",
    severity: "high",
    driftType: "Ownership Drift",
    timestamp: "2 min ago",
    explanation:
      "GraphRAG detected an undisclosed UBO link via Offshore Holding Ltd. Triple added with HIGH confidence.",
    status: "open",
  },
  {
    id: "alert_003",
    customerId: "binance",
    customerName: "Binance Holdings",
    title: "Transaction pattern anomaly",
    severity: "elevated",
    driftType: "Transaction Drift",
    timestamp: "14 min ago",
    explanation: "TimeGPT anomaly_score=0.91 — projected 3× volume spike within 5 days.",
    status: "open",
  },
  {
    id: "alert_005",
    customerId: "tesla",
    customerName: "Tesla",
    title: "Geographic drift detected",
    severity: "medium",
    driftType: "Geographic Drift",
    timestamp: "1h ago",
    explanation: "Counterparty jurisdictions shifted from CH to KY over last 30 days.",
    status: "open",
  },
  {
    id: "alert_004",
    customerId: "amazon",
    customerName: "Amazon",
    title: "Adverse media signal",
    severity: "elevated",
    driftType: "Behavioral Drift",
    timestamp: "3h ago",
    explanation: "Loop A reconstruction error 0.62 with negative-sentiment keywords.",
    status: "investigating",
  },
  {
    id: "alert_002",
    customerId: "offshore-holding",
    customerName: "Offshore Holding Ltd",
    title: "Sanctions screening hit",
    severity: "high",
    driftType: "Compliance Drift",
    timestamp: "6h ago",
    explanation: "PEP screening surfaced a politically exposed connected party.",
    status: "open",
  },
];

export const graphNodes: GraphNode[] = [
  { id: "spacex", label: "SpaceX", type: "company", riskStatus: "elevated", driftScore: 69, lastUpdated: "2m" },
  { id: "tesla", label: "Tesla", type: "company", riskStatus: "medium", driftScore: 38, lastUpdated: "1h" },
  { id: "amazon", label: "Amazon", type: "company", riskStatus: "low", driftScore: 8, lastUpdated: "11m" },
  { id: "nvidia", label: "NVIDIA", type: "company", riskStatus: "medium", driftScore: 31, lastUpdated: "26m" },
  { id: "binance", label: "Binance Holdings", type: "company", riskStatus: "high", driftScore: 84, lastUpdated: "14m" },
  { id: "offshore", label: "Offshore Holding Ltd", type: "company", riskStatus: "high", driftScore: 71, lastUpdated: "5m" },
  { id: "unknown", label: "Unknown Entity Ltd", type: "unknown", riskStatus: "high", driftScore: 77, lastUpdated: "8m" },
  { id: "ch", label: "Switzerland", type: "jurisdiction", riskStatus: "low", driftScore: 4, lastUpdated: "1d" },
  { id: "ky", label: "Cayman Islands", type: "jurisdiction", riskStatus: "elevated", driftScore: 58, lastUpdated: "3h" },
];

export const graphEdges: GraphEdge[] = [
  { source: "spacex", target: "tesla", relationship: "common UBO: Elon Musk" },
  { source: "spacex", target: "offshore", relationship: "new beneficial-owner link", isNewlyDetected: true, severity: "high" },
  { source: "offshore", target: "unknown", relationship: "shell ownership" },
  { source: "unknown", target: "ky", relationship: "jurisdiction" },
  { source: "binance", target: "ky", relationship: "registered in" },
  { source: "binance", target: "unknown", relationship: "transactions" },
  { source: "tesla", target: "ch", relationship: "counterparty" },
  { source: "amazon", target: "nvidia", relationship: "supplier" },
  { source: "nvidia", target: "ch", relationship: "tax residence" },
];

export const kycDrift: Record<string, KYCDriftRecord> = {
  spacex: {
    client_id: "C-54871",
    overall_drift_severity: "high",
    rekyc_required: true,
    summary: "This customer no longer fully matches the original KYC baseline.",
    drifted_fields: [
      {
        field: "jurisdiction",
        baseline_value: "CH",
        current_value: "KY",
        drift_severity: "high",
        source: "OpenCorporates",
      },
      {
        field: "beneficial_owners",
        baseline_value: "Jane Smith",
        current_value: "Jane Smith, Unknown Entity Ltd",
        drift_severity: "high",
        source: "GLEIF",
      },
    ],
  },
};

export const reasoningTraces: Record<string, AIReasoningTrace> = {
  "alert_001": {
    trace_id: "trc-9f12",
    alert_id: "alert_001",
    loop_a: {
      vae_reconstruction_error: 0.83,
      drift_threshold: 0.41,
      drift_detected: true,
      top_keywords: ["sanction", "arrest", "fraud"],
      embedding_shift_score: 0.74,
      decision: "DRIFT_EVENT emitted",
      cost_usd: 0.0,
    },
    loop_b: {
      graphrag: {
        triple_status: "added",
        new_entity: "Offshore Holding Ltd — UBO",
        timestamp_slice: "2026-06-01 to 2026-06-19",
      },
      timegpt: {
        horizon_days: 7,
        anomaly_score: 0.91,
        uncertainty: [2.1, 4.8],
        summary: "Transaction volume projected to spike 3× in 5 days",
      },
      survival: {
        model: "SumoNet",
        time_to_decay_days: 3.2,
        confidence: 0.88,
        summary: "KYC compliance expected to decay in 3.2 days",
      },
      router: {
        path: "heavy",
        reason: "T=3.2 days < 7-day threshold",
        model: "deepseek-r1",
        tokens: 4800,
        cost_usd: 0.0048,
      },
    },
    audit_citations: ["OpenCorporates#HRB123456", "GLEIF#5493001KJTIIGC8Y1R12", "NewsAPI#a91fe"],
    guardrail_checks: [
      "no hallucinated entities",
      "all citations verified",
      "no PII leaked",
      "hallucination check passed",
    ],
    hallucination_check_passed: true,
    total_tokens_used: 4800,
    total_cost_usd: 0.0048,
    decision_rationale:
      "A new UBO link to Offshore Holding Ltd was detected via two independent sources within a 19-day window, combined with adverse-media keyword shift and a forecasted 3× transaction spike. Survival model indicates KYC decay in <7 days, triggering heavy-router escalation.",
  },
};

export const governance: Record<string, GovernanceRecord> = {
  "alert_001": {
    record_id: "gov-7711",
    alert_id: "alert_001",
    status: "awaiting_analyst",
    steps: ["signal_received", "drift_gate_passed", "graph_resolved", "guardrails_passed", "routed_to_queue"],
    requires_manual_approval: true,
    approval_deadline: "2026-06-22 17:00 UTC",
    final_decision: "pending",
  },
};

export const engineLogs: { ts: string; level: "info" | "warn" | "error"; module: string; msg: string }[] = [
  { ts: "10:00:00", level: "info", module: "Loop A", msg: "RawSignal received: Binance / NewsAPI" },
  { ts: "10:00:01", level: "info", module: "Loop A", msg: "vectorized signal using SPLADE + ONNX encoder" },
  { ts: "10:00:01", level: "warn", module: "Loop A", msg: "VAE reconstruction_error=0.83 threshold=0.41" },
  { ts: "10:00:01", level: "warn", module: "Loop A", msg: "DRIFT_EVENT emitted" },
  { ts: "10:00:02", level: "info", module: "GraphRAG", msg: "BFS subgraph extracted (depth=2, nodes=37)" },
  { ts: "10:00:03", level: "warn", module: "GraphRAG", msg: "Triple resolution: beneficial owner added" },
  { ts: "10:00:04", level: "warn", module: "TimeGPT", msg: "forecast horizon=7d anomaly_score=0.91" },
  { ts: "10:00:05", level: "warn", module: "Loop B", msg: "Survival model SumoNet T=3.2d confidence=0.88" },
  { ts: "10:00:06", level: "info", module: "Router", msg: "path=heavy reason=T<7d model=deepseek-r1" },
  { ts: "10:00:07", level: "info", module: "Guardrails", msg: "no hallucinated entities · citations verified" },
  { ts: "10:00:07", level: "info", module: "Guardrails", msg: "Guardrails passed" },
  { ts: "10:00:08", level: "info", module: "Router", msg: "Alert routed to compliance queue · alert_id=a-1001" },
  { ts: "10:00:12", level: "error", module: "Loop A", msg: "encoder fallback: primary ONNX session timeout (recovered)" },
  { ts: "10:00:18", level: "info", module: "Loop A", msg: "RawSignal received: Tesla / OpenCorporates" },
  { ts: "10:00:19", level: "info", module: "Loop A", msg: "reconstruction_error=0.22 below threshold — dropped cheaply" },
];
